In [2]:
!pip install --upgrade tensorflow

In [3]:
from __future__ import print_function
import pandas as pd
import numpy as np

In [4]:
import os
os.getcwd()

'C:\\Users\\withm\\OneDrive\\Desktop\\DTSC 620 (Mon)\\Pro#2'

In [5]:
#Loading a dataset in to s date frame
spam = pd.read_csv("C:\\Users\\withm\\OneDrive\\Desktop\\DTSC 620 (Mon)\\Proj#1\\spam.csv", sep = ',')
print('Dataset Loaded as below...')
display(spam)

Dataset Loaded as below...


make  address   all   3d   our  over  remove  internet  order  mail  \
0     0.00     0.00  0.29  0.0  0.00  0.00    0.00      0.00   0.00  0.00   
1     0.46     0.00  0.00  0.0  0.00  0.00    0.00      0.00   0.00  0.00   
2     0.00     0.00  0.00  0.0  0.00  0.00    0.00      0.00   0.00  0.00   
3     0.33     0.44  0.37  0.0  0.14  0.11    0.00      0.07   0.97  1.16   
4     0.00     2.08  0.00  0.0  3.12  0.00    1.04      0.00   0.00  0.00   
...    ...      ...   ...  ...   ...   ...     ...       ...    ...   ...   
4596  0.00     0.00  0.53  0.0  0.00  0.53    0.00      0.00   0.00  0.53   
4597  0.00     0.00  0.00  0.0  0.00  0.00    0.00      0.00   0.00  0.00   
4598  0.00     0.00  0.00  0.0  0.00  0.00    0.00      0.00   0.00  0.00   
4599  0.00     0.00  0.00  0.0  0.00  0.00    0.00      0.00   0.00  0.00   
4600  0.13     0.26  0.52  0.0  0.26  0.00    0.13      0.00   0.00  0.39   

      ...  semicol  paren  bracket   bang  dollar  pound  cap_avg  cap_long  \
0     ...    0.000  0.178      0.0  0.044   0.000   0.00    1.666        10   
1     ...    0.000  0.125      0.0  0.000   0.000   0.00    1.510        10   
2     ...    0.000  0.000      0.0  0.000   0.000   0.00    1.718        11   
3     ...    0.006  0.159      0.0  0.069   0.221   0.11    3.426        72   
4     ...    0.000  0.000      0.0  0.263   0.000   0.00    1.428         4   
...   ...      ...    ...      ...    ...     ...    ...      ...       ...   
4596  ...    0.000  0.101      0.0  0.000   0.000   0.00    1.857        16   
4597  ...    0.000  0.443      0.0  0.221   0.665   0.00    3.812        15   
4598  ...    0.000  0.000      0.0  0.000   0.000   0.00    1.000         1   
4599  ...    0.000  0.218      0.0  0.218   0.000   0.00    1.687        10   
4600  ...    0.000  0.000      0.0  0.366   0.000   0.04    7.138       149   

      cap_total  Class  
0           180    ham  
1            74    ham  
2            55    ham  
3           819   spam  
4            20   spam  
...         ...    ...  
4596         52    ham  
4597         61   spam  
4598          3    ham  
4599         27    ham  
4600       1235   spam  

[4601 rows x 58 columns]

In [6]:
#Fill in the missing feature values with the most popular/frequent values in each column
spam.fillna(spam.mode().iloc[0])
display(spam)

make  address   all   3d   our  over  remove  internet  order  mail  \
0     0.00     0.00  0.29  0.0  0.00  0.00    0.00      0.00   0.00  0.00   
1     0.46     0.00  0.00  0.0  0.00  0.00    0.00      0.00   0.00  0.00   
2     0.00     0.00  0.00  0.0  0.00  0.00    0.00      0.00   0.00  0.00   
3     0.33     0.44  0.37  0.0  0.14  0.11    0.00      0.07   0.97  1.16   
4     0.00     2.08  0.00  0.0  3.12  0.00    1.04      0.00   0.00  0.00   
...    ...      ...   ...  ...   ...   ...     ...       ...    ...   ...   
4596  0.00     0.00  0.53  0.0  0.00  0.53    0.00      0.00   0.00  0.53   
4597  0.00     0.00  0.00  0.0  0.00  0.00    0.00      0.00   0.00  0.00   
4598  0.00     0.00  0.00  0.0  0.00  0.00    0.00      0.00   0.00  0.00   
4599  0.00     0.00  0.00  0.0  0.00  0.00    0.00      0.00   0.00  0.00   
4600  0.13     0.26  0.52  0.0  0.26  0.00    0.13      0.00   0.00  0.39   

      ...  semicol  paren  bracket   bang  dollar  pound  cap_avg  cap_long  \
0     ...    0.000  0.178      0.0  0.044   0.000   0.00    1.666        10   
1     ...    0.000  0.125      0.0  0.000   0.000   0.00    1.510        10   
2     ...    0.000  0.000      0.0  0.000   0.000   0.00    1.718        11   
3     ...    0.006  0.159      0.0  0.069   0.221   0.11    3.426        72   
4     ...    0.000  0.000      0.0  0.263   0.000   0.00    1.428         4   
...   ...      ...    ...      ...    ...     ...    ...      ...       ...   
4596  ...    0.000  0.101      0.0  0.000   0.000   0.00    1.857        16   
4597  ...    0.000  0.443      0.0  0.221   0.665   0.00    3.812        15   
4598  ...    0.000  0.000      0.0  0.000   0.000   0.00    1.000         1   
4599  ...    0.000  0.218      0.0  0.218   0.000   0.00    1.687        10   
4600  ...    0.000  0.000      0.0  0.366   0.000   0.04    7.138       149   

      cap_total  Class  
0           180    ham  
1            74    ham  
2            55    ham  
3           819   spam  
4            20   spam  
...         ...    ...  
4596         52    ham  
4597         61   spam  
4598          3    ham  
4599         27    ham  
4600       1235   spam  

[4601 rows x 58 columns]

In [7]:
#Define a function to creat a training and test set
#Takes dataframe and split ratio as input and ourputs train and test datasets (dataframes)
def split_trian_test(data, test_ratio):
    np.random.seed(1000)
    shuffled_indices = np.random.permutation(len(data))
    test_set_size = int(len(data) * test_ratio)
    test_indices = shuffled_indices[:test_set_size]
    train_indices = shuffled_indices[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

In [69]:
#random_state parameter fixes the seed
from sklearn.model_selection import train_test_split
spam_training_set, spam_test_set = train_test_split(spam, test_size=0.2, random_state=1)

spam_training_data, spam_training_target = spam_training_set[["make", "address", "all", "3d", "our", "over", "remove", "internet", "order", "mail", "receive", "will", "people", "report", "addresses", "free", "business", "email", "you", "credit", "your", "font", "0", "money", "hp", "hpl", "george", "650", "lab", "labs", "telnet", "857", "data", "415", "85", "technology", "1999", "parts", "pm", "direct", "cs", "meeting", "original", "project", "re", "edu", "table", "conference", "semicol", "paren", "bracket", "bang", "dollar", "pound", "cap_avg", "cap_long", "cap_total"]], spam_training_set["Class"]
spam_test_data, spam_test_target = spam_test_set[["make", "address", "all", "3d", "our", "over", "remove", "internet", "order", "mail", "receive", "will", "people", "report", "addresses", "free", "business", "email", "you", "credit", "your", "font", "0", "money", "hp", "hpl", "george", "650", "lab", "labs", "telnet", "857", "data", "415", "85", "technology", "1999", "parts", "pm", "direct", "cs", "meeting", "original", "project", "re", "edu", "table", "conference", "semicol", "paren", "bracket", "bang", "dollar", "pound", "cap_avg", "cap_long", "cap_total"]], spam_test_set["Class"]
spam_training_data.head()

make  address   all    3d   our  over  remove  internet  order  mail  \
1947  0.00      0.0  1.83  0.91  0.00  0.00    0.45       0.0   0.00  0.91   
2159  0.00      0.0  0.24  0.00  0.09  0.04    0.00       0.0   0.04  0.00   
4223  0.00      0.0  0.00  0.00  0.00  0.00    0.36       0.0   0.00  0.00   
2624  0.00      0.0  0.00  0.00  0.00  0.00    0.00       0.0   0.00  0.00   
2743  0.29      0.0  0.00  0.00  0.00  0.00    0.00       0.0   0.00  0.29   

      ...  conference  semicol  paren  bracket   bang  dollar  pound  cap_avg  \
1947  ...         0.0    0.134  0.000    0.000  2.077   0.000  0.134   12.176   
2159  ...         0.0    0.014  0.148    0.000  0.014   0.044  0.007    2.112   
4223  ...         0.0    0.000  0.000    0.000  0.053   0.053  0.000   18.370   
2624  ...         0.0    0.000  0.000    0.000  0.000   0.000  0.000    1.000   
2743  ...         0.0    0.000  0.196    0.049  0.344   0.000  0.049    1.843   

      cap_long  cap_total  
1947       338        621  
2159        26       1223  
4223       134        496  
2624         1          5  
2743        17        212  

[5 rows x 57 columns]

In [9]:
#Load library for tasks
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [11]:
#clf = RandomForestClassifier(n_estimators = 1000)
#clf = DecisionTreeClassifier(critierion="entropy")
clf_dt = DecisionTreeClassifier(criterion = "entropy")
#clf = KNeiborsClassifier(n_neighbors = 100)
clf_lr = LogisticRegression()
clf_gnb = GaussianNB()
eclf = VotingClassifier(estimators = [('DT', clf_dt), ('LR', clf_lr),('GNB', clf_gnb)], voting = 'hard')
eclf.fit(spam_training_data, spam_training_target)

C:\Users\withm\miniconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


VotingClassifier(estimators=[('DT',
                              DecisionTreeClassifier(criterion='entropy')),
                             ('LR', LogisticRegression()),
                             ('GNB', GaussianNB())])

In [17]:
#Reporting Task (1)-1
spam_test_target_predict = eclf.predict(spam_test_data)
confusion_matrix(spam_test_target, spam_test_target_predict)

array([[545,  39],
       [ 31, 385]], dtype=int64)

In [18]:
classification_report(spam_test_target, spam_test_target_predict)

'              precision    recall  f1-score   support\n\n         ham       0.95      0.93      0.94       584\n        spam       0.91      0.93      0.92       416\n\n    accuracy                           0.93      1000\n   macro avg       0.93      0.93      0.93      1000\nweighted avg       0.93      0.93      0.93      1000\n'

In [19]:
accuracy_score(spam_test_target, spam_test_target_predict)

0.93

In [20]:
#Reporting Task (1)-2
clf = AdaBoostClassifier(n_estimators=200)
clf.fit(spam_training_data, spam_training_target)

AdaBoostClassifier(n_estimators=200)

In [24]:
spam_test_target_predict = clf.predict(spam_test_data)
confusion_matrix(spam_test_target, spam_test_target_predict)

array([[560,  24],
       [ 42, 374]], dtype=int64)

In [25]:
classification_report(spam_test_target, spam_test_target_predict)

'              precision    recall  f1-score   support\n\n         ham       0.93      0.96      0.94       584\n        spam       0.94      0.90      0.92       416\n\n    accuracy                           0.93      1000\n   macro avg       0.93      0.93      0.93      1000\nweighted avg       0.93      0.93      0.93      1000\n'

In [26]:
accuracy_score(spam_test_target, spam_test_target_predict)

0.934

In [76]:
#Reporting Task (2)
LRI = LogisticRegression()
clf = AdaBoostClassifier(n_estimators=200, base_estimator=LRI)
clf.fit(spam_training_data, spam_training_target)

C:\Users\withm\miniconda3\lib\site-packages\sklearn\ensemble\_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
C:\Users\withm\miniconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\withm\miniconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/

AdaBoostClassifier(base_estimator=LogisticRegression(), n_estimators=200)

In [41]:
spam_test_target_predict = clf.predict(spam_test_data)
confusion_matrix(spam_test_target, spam_test_target_predict)

array([[556,  28],
       [ 62, 354]], dtype=int64)

In [42]:
classification_report(spam_test_target, spam_test_target_predict)

'              precision    recall  f1-score   support\n\n         ham       0.90      0.95      0.93       584\n        spam       0.93      0.85      0.89       416\n\n    accuracy                           0.91      1000\n   macro avg       0.91      0.90      0.91      1000\nweighted avg       0.91      0.91      0.91      1000\n'

In [43]:
accuracy_score(spam_test_target, spam_test_target_predict)

0.91

In [51]:
#Reporting Task (3)-1; 50% training + 50% testing
spam_test_target_predict = clf.predict(spam_test_data)
confusion_matrix(spam_test_target, spam_test_target_predict)

array([[1323,   65],
       [ 144,  768]], dtype=int64)

In [52]:
classification_report(spam_test_target, spam_test_target_predict)

'              precision    recall  f1-score   support\n\n         ham       0.90      0.95      0.93      1388\n        spam       0.92      0.84      0.88       912\n\n    accuracy                           0.91      2300\n   macro avg       0.91      0.90      0.90      2300\nweighted avg       0.91      0.91      0.91      2300\n'

In [53]:
accuracy_score(spam_test_target, spam_test_target_predict)

0.9091304347826087

In [61]:
#Reporting Task (3)-2; 60% training + 40% testing
spam_test_target_predict = clf.predict(spam_test_data)
confusion_matrix(spam_test_target, spam_test_target_predict)

array([[1063,   55],
       [ 108,  615]], dtype=int64)

In [62]:
classification_report(spam_test_target, spam_test_target_predict)

'              precision    recall  f1-score   support\n\n         ham       0.91      0.95      0.93      1118\n        spam       0.92      0.85      0.88       723\n\n    accuracy                           0.91      1841\n   macro avg       0.91      0.90      0.91      1841\nweighted avg       0.91      0.91      0.91      1841\n'

In [63]:
accuracy_score(spam_test_target, spam_test_target_predict)

0.9114611624117328

In [66]:
#Reporting Task (3)-3; 70% training + 30% testing
spam_test_target_predict = clf.predict(spam_test_data)
confusion_matrix(spam_test_target, spam_test_target_predict)

array([[781,  47],
       [ 79, 474]], dtype=int64)

In [67]:
classification_report(spam_test_target, spam_test_target_predict)

'              precision    recall  f1-score   support\n\n         ham       0.91      0.94      0.93       828\n        spam       0.91      0.86      0.88       553\n\n    accuracy                           0.91      1381\n   macro avg       0.91      0.90      0.90      1381\nweighted avg       0.91      0.91      0.91      1381\n'

In [68]:
accuracy_score(spam_test_target, spam_test_target_predict)

0.9087617668356264

In [71]:
#Reporting Task (3)-4; 80% training + 20% testing
spam_test_target_predict = clf.predict(spam_test_data)
confusion_matrix(spam_test_target, spam_test_target_predict)

array([[509,  24],
       [ 60, 328]], dtype=int64)

In [72]:
classification_report(spam_test_target, spam_test_target_predict)

'              precision    recall  f1-score   support\n\n         ham       0.89      0.95      0.92       533\n        spam       0.93      0.85      0.89       388\n\n    accuracy                           0.91       921\n   macro avg       0.91      0.90      0.91       921\nweighted avg       0.91      0.91      0.91       921\n'

In [73]:
accuracy_score(spam_test_target, spam_test_target_predict)

0.9087947882736156